# Generated by Django 2.2 on 2020-11-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('nss', models.CharField(max_length=100)),
                ('npsn', models.CharField(max_length=100)),
                ('school_type', models.CharField(choices=[('Sekolah_Nasional', 'Sekolah_Nasional'), ('Sekolah_Nasional_Plus', 'Sekolah_Nasional_Plus'), ('Sekolah_Internasional', 'Sekolah_Internasional'), ('Sekolah_Alam', 'Sekolah_Alam'), ('Madrasah', 'Madrasah'), ('Sekolah_Rumah', 'Sekolah_Rumah')], default='1', max_length=25)),
                ('school_address_street', models.CharField(max_length=100)),
                ('school_address_province', models.CharField(max_length=100)),
                ('school_address_city', models.CharField(max_length=100)),
                ('school_address_district', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('school_status', models.CharField(max_length=100)),
                ('acreditation_score', models.CharField(max_length=100)),
            ],
        ),
    ]
