# Generated by Django 2.2 on 2020-11-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0003_auto_20201130_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='school_type',
            field=models.CharField(choices=[('Sekolah Nasional', 'Sekolah Nasional'), ('Sekolah Nasional Plus', 'Sekolah Nasional Plus'), ('Sekolah Internasional', 'Sekolah Internasional'), ('Sekolah Alam', 'Sekolah Alam'), ('Madrasah', 'Madrasah'), ('Sekolah Rumah', 'Sekolah Rumah')], default='1', max_length=25),
        ),
    ]
