# Generated by Django 2.2 on 2020-12-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0004_auto_20201130_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('birth_place', models.CharField(max_length=100)),
                ('birth_date', models.DateField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=25, null=True)),
                ('status', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobile_phone', models.CharField(max_length=100)),
                ('golongan', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=50, null=True)),
                ('certificat_number', models.CharField(max_length=100)),
                ('educational_qualifications', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
            ],
        ),
    ]
