# Generated by Django 2.2 on 2020-12-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0005_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='certificat_number',
            new_name='certificate_number',
        ),
    ]
