# Generated by Django 2.2 on 2020-12-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiation', '0007_auto_20201201_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='golongan',
            field=models.CharField(blank=True, choices=[('1', '1A'), ('2', '1B'), ('3', '1C'), ('4', '1D'), ('5', '2A'), ('6', '2B'), ('7', '2C'), ('8', '2D'), ('9', '3A'), ('10', '3B'), ('11', '3C'), ('12', '3D'), ('13', '4A'), ('14', '4B'), ('15', '4C'), ('16', '4D')], max_length=50, null=True),
        ),
    ]
