# Generated by Django 2.2 on 2020-11-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberschool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='schools_name',
            new_name='school_name',
        ),
    ]
