# Generated by Django 3.1.4 on 2020-12-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='International',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_origin_international', models.CharField(choices=[('USA', 'America'), ('AUS', 'Australia')], max_length=4)),
                ('title_international', models.CharField(max_length=200)),
                ('year_of_curriculum_international', models.CharField(max_length=10)),
                ('subject_international', models.CharField(max_length=100)),
                ('level_international', models.CharField(choices=[('01', 'SD1'), ('02', 'SD2'), ('03', 'SD3'), ('04', 'SD4'), ('05', 'SD5'), ('06', 'SD6'), ('07', 'SMP1'), ('08', 'SMP2'), ('09', 'SMP3'), ('10', 'SMA1'), ('11', 'SMA2'), ('12', 'SMA3')], max_length=2)),
                ('content_international', models.TextField(max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_origin_local', models.CharField(choices=[('RI', 'Indonesia'), ('USA', 'America'), ('AUS', 'Australia')], max_length=4)),
                ('title_local', models.CharField(max_length=200)),
                ('year_of_curricullum_local', models.CharField(max_length=10)),
                ('subject_local', models.CharField(max_length=100)),
                ('level_local', models.CharField(choices=[('01', 'SD1'), ('02', 'SD2'), ('03', 'SD3'), ('04', 'SD4'), ('05', 'SD5'), ('06', 'SD6'), ('07', 'SMP1'), ('08', 'SMP2'), ('09', 'SMP3'), ('10', 'SMA1'), ('11', 'SMA2'), ('12', 'SMA3')], max_length=3)),
                ('content_local', models.TextField(max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='National',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_origin_national', models.CharField(choices=[('RI', 'Indonesia')], default='', max_length=3)),
                ('title_national', models.CharField(max_length=200, unique=True)),
                ('year_of_curricullum_national', models.CharField(max_length=10)),
                ('subject_national', models.CharField(max_length=100)),
                ('level_national', models.CharField(choices=[('01', 'SD1'), ('02', 'SD2'), ('03', 'SD3'), ('04', 'SD4'), ('05', 'SD5'), ('06', 'SD6'), ('07', 'SMP1'), ('08', 'SMP2'), ('09', 'SMP3'), ('10', 'SMA1'), ('11', 'SMA2'), ('12', 'SMA3')], default='', max_length=3)),
                ('kompetensi_inti_national', models.CharField(choices=[('1', 'Sikap Spiritual'), ('2', 'Sikap Sosial'), ('3', 'Pengetahuan'), ('4', 'Keterampilan')], default='', max_length=1)),
                ('kompetensi_dasar_national', models.IntegerField()),
                ('content_national', models.TextField(max_length=8000)),
            ],
        ),
    ]
